import parameters.Constants as Constants
import parameters.Results as Results
from random import randrange


def initialize(
    END_DEVICE_NUMBER
    ,MIN_SF
    ,MAX_SF
    ,SUPER_GROUP_LENGTH_IN_SECONDS
    ,GROUP_ID_LENGTH_IN_BIT
    ,DEVICE_ADDRESS_LENGTH_IN_BIT
    ,SUBSCRIPTION_ID_LENGTH_IN_BIT
    ,GROUP_UPLINK_PERIOD_PERCENTAGE
    ,GROUP_MIDLINK_PERIOD_PERCENTAGE
    ,GROUP_DOWNLINK_PERIOD_PERCENTAGE
    ,BANDWIDTH_IN_HERTZ
    ,NUMBER_OF_PREAMBLE
    ,SYNCHRONIZATION_WORD
    ,SF_TO_MAC_PAYLOAD_IN_BYTE
    ,CRC
    ,IH
    ,DE
    ,CODING_RATE
):
    Constants.END_DEVICE_NUMBER = END_DEVICE_NUMBER
    Constants.MIN_SF = MIN_SF
    Constants.MAX_SF = MAX_SF
    Constants.SFs = [sf for sf in range(Constants.MIN_SF, Constants.MAX_SF + 1)]
    Constants.EXPONENTIAL_DIST_SIZE = Constants.MAX_SF - Constants.MIN_SF + 1
    Constants.EXPONENTIAL_DIST_SCALE = 1

    Constants.SUPER_GROUP_LENGTH_IN_SECONDS = SUPER_GROUP_LENGTH_IN_SECONDS
    Constants.GROUP_ID_LENGTH_IN_BIT = GROUP_ID_LENGTH_IN_BIT
    Constants.DEVICE_ADDRESS_LENGTH_IN_BIT = DEVICE_ADDRESS_LENGTH_IN_BIT
    Constants.SUBSCRIPTION_ID_LENGTH_IN_BIT = SUBSCRIPTION_ID_LENGTH_IN_BIT

    # their sum should be equal to 1.
    Constants.GROUP_UPLINK_PERIOD_PERCENTAGE = GROUP_UPLINK_PERIOD_PERCENTAGE
    Constants.GROUP_MIDLINK_PERIOD_PERCENTAGE = GROUP_MIDLINK_PERIOD_PERCENTAGE
    Constants.GROUP_DOWNLINK_PERIOD_PERCENTAGE = GROUP_DOWNLINK_PERIOD_PERCENTAGE

    # they are for calculation of the time on air
    Constants.BANDWIDTH_IN_HERTZ = BANDWIDTH_IN_HERTZ
    Constants.NUMBER_OF_PREAMBLE = NUMBER_OF_PREAMBLE
    Constants.SYNCHRONIZATION_WORD = SYNCHRONIZATION_WORD
    Constants.SF_TO_MAC_PAYLOAD_IN_BYTE = SF_TO_MAC_PAYLOAD_IN_BYTE
    Constants.CRC = CRC
    Constants.IH = IH
    Constants.DE = DE
    Constants.CODING_RATE = CODING_RATE

    Results.BOOLEAN_EXP_FOR_SAME_ACK = ''
    Results.DEVICE_ID_LENGTH_IN_BIT_SAME_ACK = 0
    Results.MAC_PAYLOAD_IN_BIT_SAME_ACK = 0
    Results.BOOLEAN_EXP_FOR_DIFFERENT_ACK = {}
    Results.DEVICE_ID_LENGTH_IN_BIT_DIFFERENT_ACK = {}
    Results.MAC_PAYLOAD_IN_BIT_DIFFERENT_ACK = {}
    Results.SPREADING_FACTOR_BASED_NUMBER_OF_END_DEVICES = {}
    Results.NUMBER_OF_TRANSMITTERS = 0
    Results.NUMBER_OF_SUSPENDED_DEVICES = 0
    Results.NUMBER_OF_FAILED_DEVICES = 0

