from processors.Preprocessor import initialize
from processors.Mainprocessor import run

END_DEVICE_NUMBER = 25000

MIN_SF = 7
MAX_SF = 12

EXPONENTIAL_DIST_SIZE = MAX_SF - MIN_SF + 1
EXPONENTIAL_DIST_SCALE = 1

SUPER_GROUP_LENGTH_IN_SECONDS = 15
DEVICE_ADDRESS_LENGTH_IN_BIT = 32
SUBSCRIPTION_ID_LENGTH_IN_BIT = 24

# they are for calculation of the time on air
BANDWIDTH_IN_HERTZ = 125000
NUMBER_OF_PREAMBLE = 8
SYNCHRONIZATION_WORD = 8
SF_TO_MAC_PAYLOAD_IN_BYTE = {7: 250, 8: 250, 9: 123, 10: 59, 11: 59, 12: 59}
CRC = 1
IH = 0
DE = 0
CODING_RATE = 1

DUTY_CYCLE_IN_PERCENTAGE = 1

SIMULATION_LIFE_TIME_IN_SECONDS = 700

initialize(
    END_DEVICE_NUMBER
    ,MIN_SF
    ,MAX_SF
    ,SUPER_GROUP_LENGTH_IN_SECONDS
    ,DEVICE_ADDRESS_LENGTH_IN_BIT
    ,SUBSCRIPTION_ID_LENGTH_IN_BIT
    ,BANDWIDTH_IN_HERTZ
    ,NUMBER_OF_PREAMBLE
    ,SYNCHRONIZATION_WORD
    ,SF_TO_MAC_PAYLOAD_IN_BYTE
    ,CRC
    ,IH
    ,DE
    ,CODING_RATE
    ,DUTY_CYCLE_IN_PERCENTAGE
    ,SIMULATION_LIFE_TIME_IN_SECONDS)
run()