from processors.Preprocessor import initialize
from processors.Mainprocessor import run
from processors.Postprocessor import print_results

END_DEVICE_NUMBER = 100000

MIN_SF = 7
MAX_SF = 12

EXPONENTIAL_DIST_SIZE = MAX_SF - MIN_SF + 1
EXPONENTIAL_DIST_SCALE = 1

SUPER_GROUP_LENGTH_IN_SECONDS = 100
GROUP_ID_LENGTH_IN_BIT = 6
DEVICE_ADDRESS_LENGTH_IN_BIT = 32
SUBSCRIPTION_ID_LENGTH_IN_BIT = 24

# their sum should be equal to 1.
GROUP_UPLINK_PERIOD_PERCENTAGE = 0.5
GROUP_MIDLINK_PERIOD_PERCENTAGE = 0
GROUP_DOWNLINK_PERIOD_PERCENTAGE = 0.5

# they are for calculation of the time on air
BANDWIDTH_IN_HERTZ = 125000
NUMBER_OF_PREAMBLE = 8
SYNCHRONIZATION_WORD = 8
SF_TO_MAC_PAYLOAD_IN_BYTE = {7: 250, 8: 250, 9: 123, 10: 59, 11: 59, 12: 59}
CRC = 1
IH = 0
DE = 0
CODING_RATE = 1

initialize(
    END_DEVICE_NUMBER
    ,MIN_SF
    ,MAX_SF
    ,SUPER_GROUP_LENGTH_IN_SECONDS
    ,GROUP_ID_LENGTH_IN_BIT
    ,DEVICE_ADDRESS_LENGTH_IN_BIT
    ,SUBSCRIPTION_ID_LENGTH_IN_BIT
    ,GROUP_UPLINK_PERIOD_PERCENTAGE
    ,GROUP_MIDLINK_PERIOD_PERCENTAGE
    ,GROUP_DOWNLINK_PERIOD_PERCENTAGE
    ,BANDWIDTH_IN_HERTZ
    ,NUMBER_OF_PREAMBLE
    ,SYNCHRONIZATION_WORD
    ,SF_TO_MAC_PAYLOAD_IN_BYTE
    ,CRC
    ,IH
    ,DE
    ,CODING_RATE)
run()
print_results()
