END_DEVICE_NUMBER = 1000

MIN_SF = 7
MAX_SF = 12

SFs = [sf for sf in range(MIN_SF, MAX_SF+1)]

BERNOULLI_DIST_SIZE = 1000
BERNOULLI_DIST_P = 0.0004

EXPONENTIAL_DIST_SIZE = MAX_SF - MIN_SF + 1
EXPONENTIAL_DIST_SCALE = 1
