from random import randrange

END_DEVICE_NUMBER = 1000

MIN_SF = 7
MAX_SF = 12
SFs = [sf for sf in range(MIN_SF, MAX_SF+1)]

BERNOULLI_DIST_SIZE = END_DEVICE_NUMBER
BERNOULLI_DIST_P = float(randrange(1, 10)) / float(END_DEVICE_NUMBER)

EXPONENTIAL_DIST_SIZE = MAX_SF - MIN_SF + 1
EXPONENTIAL_DIST_SCALE = 1

END_DEVICE_MESSAGE_PERIOD = 0.01
GATEWAY_MESSAGE_PERIOD = 60
